version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./docker.d/nginx/site.conf:/etc/nginx/conf.d/default.conf
            - ./public:/var/www/html
        networks:
            - app-network
    php:
        image: php:fpm
        volumes:
            - ./:/var/www
            - ./docker.d/php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
#            - ./docker.d/php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.conf
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
